### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by bazmonk**
I'm merging in what I'm calling v0.9 of this code.  It's a complete re-write and I think it's ready for users to try.

### CODE REVIEW

**Comment by angeleusebio** [comment]
V0.9 dont Work with my digidurdy, remain dead. O return to v0.3 and work again.
Thanks for tour work

**Comment by bazmonk** [comment]
What part failed?

**Comment by bazmonk** [comment]
@angeleusebio could you post the output from Teensyduino when you built it?  Do you have the Blue OLED by any chance?

**Comment by angeleusebio** [comment]
Sorry, was my fault, I try it again after actualize librarys and it works.
Thanks again
Good day

**Comment by bazmonk** [comment]
Excellent!

**Pull request merged**
